name: NodeJS runner

on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: âœ… Check Versions
        run: |
          node --version
          npm --version
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v3
      - run: npm install
      - name: ðŸ”Ž Check IP
        run: curl https://api.ipify.org
      - name: ðŸš€ Deploy
        run: node .
